name: Docker Build

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pixelfed

jobs:
  create-release-apache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ env.IMAGE_NAME }}
          dockerfile: ./contrib/docker/Dockerfile.apache
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  create-release-fpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ env.IMAGE_NAME }}-fpm
          dockerfile: ./contrib/docker/Dockerfile.fpm
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
